force-app/main/default/objects/AccountOrg1__x/AccountOrg1__x.object-meta.xml
<CustomObject>
    <externalDataSource>Org1</externalDataSource>
    <externalName>Account</externalName>
    <label>AccountOrg1</label>
    <pluralLabel>AccountsOrg1</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountOrg1__x/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <externalDeveloperName>Name</externalDeveloperName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/TestSimilarAccountsController.cls
@isTest
private class TestSimilarAccountsController {
    static testMethod void run() {

        List<AccountOrg1__x> accountsOrg1 = new List<AccountOrg1__x>(); 
        AccountOrg1__x accountOrg1 = new AccountOrg1__x(
             Account_Name__c = 'Test Data',
             Website__c = 'https://test.com/'
         );
         accountsOrg1.add(accountOrg1);
         ObjectManager.setMock(new MockInterfaceOverride(accountsOrg1));

        Test.startTest();
        List<AccountOrg1__x> result = SimilarAccountsController.getSimilarAccountsAction('Test', 'test');
        Test.stopTest();

        System.assertEquals(1, result.size());
    }
}