force-app/main/default/objects/AccountOrg1__x/AccountOrg1__x.object-meta.xml
<CustomObject>
    <externalDataSource>Org1</externalDataSource>
    <externalName>Account</externalName>
    <label>AccountOrg1</label>
    <pluralLabel>AccountsOrg1</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountOrg1__x/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <externalDeveloperName>Name</externalDeveloperName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Account_from_Org1__c/Related_Account_from_Org1__c.object-meta.xml
<CustomObject>
    <label>Related Account from Org1</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Accounts from Org1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Account_from_Org1__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Accounts from Org1</relationshipLabel>
    <relationshipName>Related_Accounts_from_Org1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Related_Account_from_Org1__c/fields/Account_Website__c.field-meta.xml
<CustomField>
    <fullName>Account_Website__c</fullName>
    <label>Account Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Related_Account_from_Org1__c/fields/External_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Account_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Account Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelatedAccounts.cls
public class RelatedAccounts {
    
    public static List<AccountOrg1__x> getSimilarExternalAccounts(String accountName, String accountWebsite){
        accountName = '%' + accountName + '%';
        String accountsQuery = 'SELECT Account_Name__c, Website__c FROM AccountOrg1__x WHERE Account_Name__c  LIKE :accountName';
        if (String.isEmpty(accountWebsite) == false){
            accountWebsite = '%' + accountWebsite + '%';
            accountsQuery += ' OR Website__c like :accountWebsite';
        }
        accountsQuery += ' LIMIT 20';
        return ObjectManager.records(Database.query(accountsQuery));
    }

    public static void updateRelatedAccounts(Account account){

        List<AccountOrg1__x> similarExternalAccounts = RelatedAccounts.getSimilarExternalAccounts(account.Name, account.Website);

        List<Related_Account_from_Org1__c> oldRelatedAccounts = [Select Id from Related_Account_from_Org1__c Where Account_Id__c =: account.Id];
        if (oldRelatedAccounts.size() > 0){
            delete oldRelatedAccounts;
        }

        List<Related_Account_from_Org1__c> relatedAccountsToInsert = new List<Related_Account_from_Org1__c>();

        for (AccountOrg1__x externalAccount : similarExternalAccounts){
            Related_Account_from_Org1__c relatedAccount = new Related_Account_from_Org1__c(
                Account_Id__c = account.id,
                External_Account_Id__c = externalAccount.Id,
                Name = externalAccount.Account_Name__c,
                Account_Website__c = externalAccount.Website__c
            );
            relatedAccountsToInsert.add(relatedAccount);
        }
        if (relatedAccountsToInsert.size() > 0){
            insert relatedAccountsToInsert;
        }
    }

    @future(callout = true)
    public static void updateRelatedAccountsFuture(String accountId){
        Account account = [Select Name, Website from Account Where Id =: accountId];
        RelatedAccounts.updateRelatedAccounts(account);
    }

}