force-app/main/default/objects/AccountOrg1__x/AccountOrg1__x.object-meta.xml
<CustomObject>
    <externalDataSource>Org1</externalDataSource>
    <externalName>Account</externalName>
    <label>AccountOrg1</label>
    <pluralLabel>AccountsOrg1</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountOrg1__x/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <externalDeveloperName>Name</externalDeveloperName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_Account_from_Org1__c/Related_Account_from_Org1__c.object-meta.xml
<CustomObject>
    <label>Related Account from Org1</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Accounts from Org1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Account_from_Org1__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related Accounts from Org1</relationshipLabel>
    <relationshipName>Related_Accounts_from_Org1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/TestRefreshRelatedAccountsController.cls
@isTest
private class TestRefreshRelatedAccountsController {
    static testMethod void run() {
        Account accountModel = new Account(
            Name = 'Test Data',
            Website = 'https://test.com/'
        );
        insert accountModel;

        List<AccountOrg1__x> accountsOrg1 = new List<AccountOrg1__x>(); 
        AccountOrg1__x accountOrg1 = new AccountOrg1__x(
            Account_Name__c = 'Test Data',
            Website__c = 'https://test.com/'
        );
        accountsOrg1.add(accountOrg1);
        ObjectManager.setMock(new MockInterfaceOverride(accountsOrg1));

        Apexpages.StandardController stdController = new Apexpages.StandardController(accountModel);

        ApexPages.currentPage().getParameters().put('accountId', accountModel.Id);
        RefreshRelatedAccountsController controller = new RefreshRelatedAccountsController(stdController);
        Test.startTest();
        controller.RefreshRelatedAccounts();
        List<Related_Account_from_Org1__c> relatedAccounts = [Select Id from Related_Account_from_Org1__c Where Account_Id__c =: accountModel.Id];
        Test.stopTest();

        System.assertEquals(1, relatedAccounts.size());
    }
}